### ISSUE TITLE
0.9.2, FW 051.8: No supported firmware found

### ISSUE THREAD

**Issue by fu-zhou** [hombach/ioBroker.go-e-charger#200]
Hallo Hombach,

ich habe auf meinem Go eCharger V3 gestern die 051.8 draufgemacht, im Log kommt jetzt:
`<html>
<body>

go-e-charger.0 | 2021-10-22 09:47:58.218 | error | No supported firmware found!!!
-- | -- | -- | --
go-e-charger.0 | 2021-10-22 09:47:58.217 | error | [asyncGetForeignState](): Error: The id is empty! Please provide a valid id.

</body>
</html>`

Info und Power wird scheinbar korrekt angezeigt, z.B. go-e-charger.0.Power.ChargeCurrent kann ich über die App verstellen und wird dann auch richtig in iobroker gezeigt, aber die Settings werden nicht übernommen.

Kannst du dir das mal anschauen? Ich kann gerne helfen und testen.

Kannst du auch mal darstellen, auf welche API keys (v2) du mit den Objekten deines Adapters zugreifst?

Vielen Dank vorab!

**Comment by hombach** [comment]
Hast du eine neuere Version getestet?

**Comment by fu-zhou** [comment]
ich bin mittlerweile auf die aktuellste FW gegangen - 053.1, nutze aber nur noch die MQTT-Schnittstelle
