### ISSUE TITLE
Firmware 4.0 for go-e-charger with new parameter "amx" for PWM Signalisierung.

### ISSUE THREAD

**Issue by muelmark** [hombach/ioBroker.go-e-charger#53]
Hello colleagues,
first of all: thank you for providing this adaper for iobroker - this is working great on my side.

I am not sure if you saw the latest 4.0 firmware change.  According to 
https://github.com/goecharger/go-eCharger-API-v1/commit/3d46503129e4c37cf7c55a7b70b9b56e34464daa
there was a new set parameter "amx" created in parallel to "amp" to set one and the same value. The basic difference between amx and amp is, that since firmware 040.0 there is a possibilty to change the max_load parameter only in "ram" of the machine and not writing it to the flash (and yes, it will be copied from flash during a re-boot). Flash write access is limited both from space also from lifetime, so it makes sense to use amx instead of amp for setting max_load.

Is it possible to implement something like this -that shouldn´t be a big thing. I could offer to code if my help is needed.

if firmware >= "040.0"
   use set (amx)
else
   use set (amp)

Bests,
Markus

**Comment by hombach** [comment]
Sounds like a very good idea - I will check this

**Comment by hombach** [comment]
You could do me a favour.... my charger is still on firmware 033 - I would need someone to test on 040 if the object info.firmware is filled correctly.

**Comment by muelmark** [comment]
I could of course offer check that. To reach that out two options are possible:
(1) Either there is a possiblity to read and display that amx value in iobroker (most convenient way for all users, but the you have to code both a setter and a getter :-)
(2) I could use the generated set method and set something different, see the result in the app and after reboot it should be restored to amp (which is different)

**Comment by hombach** [comment]
At the moment it's sufficient if you could verify that info.firmware in objects is 040 in your system

**Comment by hombach** [comment]
OK - my vault - two agents tried to write o the same box simultaneously.
It's working in my setup. Adapter version 0.4.0

**Comment by hombach** [comment]
Release of version 0.4.0
